//! PKI state file — tracks all certificates generated by a ceremony.
//!
//! The state file (`pki-state.json`) is written alongside ceremony outputs and
//! records metadata for every certificate: serial numbers, fingerprints, validity
//! windows, parent relationships, and revocation status. This enables tooling to
//! inspect, audit, and manage a PKI hierarchy after the ceremony completes.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

/// Filename for the PKI state file within an output directory.
const STATE_FILENAME: &str = "pki-state.json";

// ═══════════════════════════════════════════════════════════════
// Types
// ═══════════════════════════════════════════════════════════════

/// Top-level PKI state — serialized as `pki-state.json`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PkiState {
    /// Schema version (currently 1).
    pub version: u32,
    /// Generator identifier (e.g. "hedonistic-pki v1.0.0").
    pub generator: String,
    /// ISO-8601 timestamp of state creation.
    pub created_at: String,
    /// The ceremony config that produced this state, stored as opaque JSON
    /// so the state file is self-contained even if the config schema evolves.
    pub ceremony_config: serde_json::Value,
    /// One record per generated certificate, in generation order.
    pub certs: Vec<CertRecord>,
}

/// Metadata for a single certificate in the hierarchy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CertRecord {
    /// Unique name from the ceremony config (e.g. "root-ca").
    pub name: String,
    /// X.509 Common Name.
    pub cn: String,
    /// Certificate serial number in hex.
    pub serial_hex: String,
    /// SHA-256 fingerprint of the DER-encoded certificate.
    pub fingerprint_sha256: String,
    /// Key algorithm (e.g. "Rsa4096", "Ed25519").
    pub algorithm: String,
    /// Certificate type from config (e.g. "root", "intermediate", "leaf").
    pub cert_type: String,
    /// Parent cert name, or `None` for root CAs.
    pub parent: Option<String>,
    /// Not-before date (ISO-8601).
    pub not_before: String,
    /// Not-after date (ISO-8601).
    pub not_after: String,
    /// Timestamp when this cert was generated (ISO-8601).
    pub generated_at: String,
    /// Whether the cert spec was marked offline.
    pub offline: bool,
    /// Whether this certificate has been revoked.
    pub revoked: bool,
    /// Timestamp of revocation (ISO-8601), if revoked.
    pub revoked_at: Option<String>,
}

// ═══════════════════════════════════════════════════════════════
// Timestamp helper
// ═══════════════════════════════════════════════════════════════

/// ISO-8601 UTC timestamp using the `time` crate already in dependencies.
pub fn now_iso8601() -> String {
    let now = time::OffsetDateTime::now_utc();
    format!(
        "{:04}-{:02}-{:02}T{:02}:{:02}:{:02}Z",
        now.year(),
        now.month() as u8,
        now.day(),
        now.hour(),
        now.minute(),
        now.second()
    )
}

// ═══════════════════════════════════════════════════════════════
// Implementation
// ═══════════════════════════════════════════════════════════════

impl PkiState {
    /// Create a new empty state with version 1 and the current timestamp.
    ///
    /// The `config` parameter is stored verbatim so the state file captures
    /// exactly what was fed into the ceremony.
    pub fn new(config: &serde_json::Value) -> Self {
        Self {
            version: 1,
            generator: format!("hedonistic-pki v{}", env!("CARGO_PKG_VERSION")),
            created_at: now_iso8601(),
            ceremony_config: config.clone(),
            certs: Vec::new(),
        }
    }

    /// Get current ISO-8601 timestamp.
    pub fn now_iso8601() -> String {
        now_iso8601()
    }

    /// Append a certificate record to the state.
    pub fn add_cert(&mut self, record: CertRecord) {
        self.certs.push(record);
    }

    /// Persist the state as pretty-printed JSON to `<dir>/pki-state.json`.
    pub fn save(&self, dir: &Path) -> Result<()> {
        let path = dir.join(STATE_FILENAME);
        let json =
            serde_json::to_string_pretty(self).context("Failed to serialize PKI state to JSON")?;
        fs::write(&path, json.as_bytes())
            .with_context(|| format!("Failed to write PKI state to {}", path.display()))?;
        Ok(())
    }

    /// Load state from `<dir>/pki-state.json`.
    pub fn load(dir: &Path) -> Result<Self> {
        let path = dir.join(STATE_FILENAME);
        let content = fs::read_to_string(&path)
            .with_context(|| format!("Failed to read PKI state from {}", path.display()))?;
        let state: Self = serde_json::from_str(&content)
            .with_context(|| format!("Failed to parse PKI state from {}", path.display()))?;
        Ok(state)
    }

    /// Look up a certificate record by name.
    pub fn find_cert(&self, name: &str) -> Option<&CertRecord> {
        self.certs.iter().find(|c| c.name == name)
    }

    /// Return all certificates whose parent matches `parent_name`.
    pub fn find_children(&self, parent_name: &str) -> Vec<&CertRecord> {
        self.certs
            .iter()
            .filter(|c| c.parent.as_deref() == Some(parent_name))
            .collect()
    }

    /// Mark a certificate as revoked with the current timestamp.
    ///
    /// No-op if the name is not found or already revoked.
    pub fn mark_revoked(&mut self, name: &str) {
        if let Some(cert) = self.certs.iter_mut().find(|c| c.name == name)
            && !cert.revoked
        {
            cert.revoked = true;
            cert.revoked_at = Some(now_iso8601());
        }
    }
}

// ═══════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    fn tempdir() -> std::path::PathBuf {
        static COUNTER: AtomicU64 = AtomicU64::new(0);
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let dir = std::env::temp_dir().join(format!(
            "hedonistic-pki-test-state-{}-{}",
            std::process::id(),
            id,
        ));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        dir
    }

    fn sample_config() -> serde_json::Value {
        serde_json::json!({
            "name": "test-pki",
            "organization": "Test LLC",
            "hierarchy": []
        })
    }

    fn sample_record(name: &str, parent: Option<&str>) -> CertRecord {
        CertRecord {
            name: name.to_string(),
            cn: format!("Test {name}"),
            serial_hex: "01".to_string(),
            fingerprint_sha256: "abcdef1234567890".to_string(),
            algorithm: "Rsa4096".to_string(),
            cert_type: if parent.is_none() { "root" } else { "leaf" }.to_string(),
            parent: parent.map(|s| s.to_string()),
            not_before: "2026-01-01T00:00:00Z".to_string(),
            not_after: "2046-01-01T00:00:00Z".to_string(),
            generated_at: "2026-03-19T00:00:00Z".to_string(),
            offline: parent.is_none(),
            revoked: false,
            revoked_at: None,
        }
    }

    #[test]
    fn new_state_has_version_1() {
        let state = PkiState::new(&sample_config());
        assert_eq!(state.version, 1);
        assert!(state.generator.starts_with("hedonistic-pki v"));
        assert!(!state.created_at.is_empty());
        assert!(state.certs.is_empty());
    }

    #[test]
    fn add_cert_appends() {
        let mut state = PkiState::new(&sample_config());
        state.add_cert(sample_record("root-ca", None));
        state.add_cert(sample_record("leaf", Some("root-ca")));
        assert_eq!(state.certs.len(), 2);
    }

    #[test]
    fn find_cert_by_name() {
        let mut state = PkiState::new(&sample_config());
        state.add_cert(sample_record("root-ca", None));
        state.add_cert(sample_record("leaf", Some("root-ca")));

        let found = state.find_cert("root-ca");
        assert!(found.is_some());
        assert_eq!(found.unwrap().cn, "Test root-ca");

        assert!(state.find_cert("nonexistent").is_none());
    }

    #[test]
    fn find_children_returns_matching() {
        let mut state = PkiState::new(&sample_config());
        state.add_cert(sample_record("root-ca", None));
        state.add_cert(sample_record("inter", Some("root-ca")));
        state.add_cert(sample_record("leaf-a", Some("inter")));
        state.add_cert(sample_record("leaf-b", Some("inter")));

        let children = state.find_children("inter");
        assert_eq!(children.len(), 2);

        let root_children = state.find_children("root-ca");
        assert_eq!(root_children.len(), 1);
        assert_eq!(root_children[0].name, "inter");

        let none_children = state.find_children("nonexistent");
        assert!(none_children.is_empty());
    }

    #[test]
    fn mark_revoked_sets_fields() {
        let mut state = PkiState::new(&sample_config());
        state.add_cert(sample_record("root-ca", None));

        assert!(!state.certs[0].revoked);
        assert!(state.certs[0].revoked_at.is_none());

        state.mark_revoked("root-ca");

        assert!(state.certs[0].revoked);
        assert!(state.certs[0].revoked_at.is_some());
    }

    #[test]
    fn mark_revoked_is_idempotent() {
        let mut state = PkiState::new(&sample_config());
        state.add_cert(sample_record("root-ca", None));

        state.mark_revoked("root-ca");
        let first_ts = state.certs[0].revoked_at.clone();

        state.mark_revoked("root-ca");
        assert_eq!(state.certs[0].revoked_at, first_ts);
    }

    #[test]
    fn mark_revoked_nonexistent_is_noop() {
        let mut state = PkiState::new(&sample_config());
        state.mark_revoked("ghost"); // should not panic
    }

    #[test]
    fn save_and_load_roundtrip() {
        let dir = tempdir();

        let mut state = PkiState::new(&sample_config());
        state.add_cert(sample_record("root-ca", None));
        state.add_cert(sample_record("leaf", Some("root-ca")));
        state.save(&dir).unwrap();

        let loaded = PkiState::load(&dir).unwrap();
        assert_eq!(loaded.version, 1);
        assert_eq!(loaded.certs.len(), 2);
        assert_eq!(loaded.certs[0].name, "root-ca");
        assert_eq!(loaded.certs[1].name, "leaf");
        assert_eq!(loaded.ceremony_config["name"], "test-pki");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn load_nonexistent_errors() {
        let result = PkiState::load(Path::new("/nonexistent/path"));
        assert!(result.is_err());
    }

    #[test]
    fn serde_roundtrip_json() {
        let mut state = PkiState::new(&sample_config());
        state.add_cert(sample_record("root-ca", None));

        let json = serde_json::to_string_pretty(&state).unwrap();
        let parsed: PkiState = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed.version, state.version);
        assert_eq!(parsed.certs.len(), 1);
        assert_eq!(parsed.certs[0].name, "root-ca");
    }
}
